In [1]:
import pandas as pd                  #importing pandas
lung_cancer = pd.read_csv("survey lung cancer.csv")       #importing csv 
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
lung_cancer.head()            #viewing the data

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      M   69        1               2        2              1   
1      M   74        2               1        1              1   
2      F   59        1               1        1              2   
3      M   63        2               2        2              1   
4      F   63        1               2        1              1   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
0                    2                      2           2         YES  
1                    2                      2           2         YES  
2                    2                      1           2          NO  
3                    1                      2           2          NO  
4                    2                      1           1          NO

In [2]:
print(lung_cancer.isnull().sum())         #chcking the null values
print(lung_cancer.shape)           #shape of df how many rows? and columns?

GENDER                   0
AGE                      0
SMOKING                  0
YELLOW_FINGERS           0
ANXIETY                  0
PEER_PRESSURE            0
CHRONIC DISEASE          0
FATIGUE                  0
ALLERGY                  0
WHEEZING                 0
ALCOHOL CONSUMING        0
COUGHING                 0
SHORTNESS OF BREATH      0
SWALLOWING DIFFICULTY    0
CHEST PAIN               0
LUNG_CANCER              0
dtype: int64
(309, 16)


In [3]:
duplicate = lung_cancer[lung_cancer.duplicated()]          #checking the duplicates
duplicate.shape                              #checking how many duplicates are the 

(33, 16)

In [4]:
duplicate.index             #just viewing the what are the index values of duplicatres

Int64Index([ 99, 100, 117, 199, 212, 223, 256, 275, 284, 285, 286, 287, 288,
            289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301,
            302, 303, 304, 305, 306, 307, 308],
           dtype='int64')

In [5]:
for i in duplicate.index:
    #print(i)
    lung_cancer.drop(index = [i], inplace = True)            #deleting the duplicates 

In [6]:
duplicate = lung_cancer[lung_cancer.duplicated()]
duplicate

Empty DataFrame
Columns: [GENDER, AGE, SMOKING, YELLOW_FINGERS, ANXIETY, PEER_PRESSURE, CHRONIC DISEASE, FATIGUE , ALLERGY , WHEEZING, ALCOHOL CONSUMING, COUGHING, SHORTNESS OF BREATH, SWALLOWING DIFFICULTY, CHEST PAIN, LUNG_CANCER]
Index: []

In [7]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()

In [8]:
print(lung_cancer.GENDER.unique())
print(lung_cancer.LUNG_CANCER.unique())

['M' 'F']
['YES' 'NO']


In [9]:
lung_cancer.GENDER = LE.fit_transform(lung_cancer.GENDER)
lung_cancer.LUNG_CANCER = LE.fit_transform(lung_cancer.LUNG_CANCER)

In [10]:
lung_cancer.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0       1   69        1               2        2              1   
1       1   74        2               1        1              1   
2       0   59        1               1        1              2   
3       1   63        2               2        2              1   
4       0   63        1               2        1              1   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  LUNG_CANCER  
0                    2                      2           2            1  
1                    2                      2           2            1  
2                    2                      1           2            0  
3                    1                      2           2            0  
4                    2                      1           1            0

In [11]:
X = lung_cancer.drop(["LUNG_CANCER"],axis=1)
y = lung_cancer.LUNG_CANCER

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size= 0.2, random_state = 0)

In [13]:
print(X_train.shape)
print(X_test.shape)

(220, 15)
(56, 15)


In [14]:
from sklearn.tree import DecisionTreeClassifier
DC = DecisionTreeClassifier()

DC.fit(X_train, y_train)

DecisionTreeClassifier()

In [15]:
DC.score(X_test, y_test)

0.9107142857142857

In [52]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier()

RF.fit(X_train, y_train)

RandomForestClassifier()

In [53]:
RF.score(X_test, y_test)

0.8913043478260869

In [54]:
RF.predict([[1,55,2,1,1,1,1,2,1,1,1,1,1,1,1]])

array([0])

In [18]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier()

KNN.fit(X_train, y_train)

KNeighborsClassifier()

In [19]:
KNN.score(X_test, y_test)

0.8214285714285714

In [48]:
KNN.predict([[1,55,2,1,1,1,1,2,1,1,1,1,1,1,1]])

C:\Users\JayaharisaiTothala\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([0])

In [21]:
from sklearn.svm import SVC
SVC = SVC()

SVC.fit(X_train, y_train)

SVC()

In [49]:
SVC.predict([[1,55,2,1,1,1,1,2,1,1,1,1,1,1,1]])

TypeError: BaseSVC.predict() missing 1 required positional argument: 'X'

In [23]:
X_test.dtypes

GENDER                   int32
AGE                      int64
SMOKING                  int64
YELLOW_FINGERS           int64
ANXIETY                  int64
PEER_PRESSURE            int64
CHRONIC DISEASE          int64
FATIGUE                  int64
ALLERGY                  int64
WHEEZING                 int64
ALCOHOL CONSUMING        int64
COUGHING                 int64
SHORTNESS OF BREATH      int64
SWALLOWING DIFFICULTY    int64
CHEST PAIN               int64
dtype: object

In [24]:
X_test.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
187       1   55        2               1        1              1   
15        0   48        1               2        2              2   
55        1   52        1               2        2              1   
74        1   61        2               1        1              1   
191       0   55        2               2        2              2   

     CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  \
187                1         2         1         1                  1   
15                 2         2         2         2                  1   
55                 2         1         2         2                  2   
74                 1         2         2         2                  2   
191                2         2         1         1                  1   

     COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  
187         1                    1                      1           1  
15          2                    2                      2           1  
55          2                    1                      2           1  
74          2                    2                      1           2  
191         1                    1                      1           1

In [26]:
SVC.score(X_test, y_test)

0.8392857142857143

In [27]:
#evaliuating
import numpy as np

X = np.array(X)
y = np.array(y)

In [28]:
from sklearn.model_selection import StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

def score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

folds = StratifiedKFold(n_splits=3)

DE =[]
RF=[]
KN =[]
SVC_score =[]

for train_index, test_index in folds.split(X, y):
    X_train, X_test, y_train, y_test = X[train_index], X[test_index], y[train_index], y[test_index]
    DE.append(score(DecisionTreeClassifier(), X_train,  X_test, y_train, y_test))
    RF.append(score(RandomForestClassifier(), X_train,  X_test, y_train, y_test))
    KN.append(score(KNeighborsClassifier(), X_train,  X_test, y_train, y_test))
    SVC_score.append(score(SVC(), X_train,  X_test, y_train, y_test))
    

In [29]:
print(DE)

[0.8804347826086957, 0.8369565217391305, 0.8478260869565217]


In [30]:
print(RF)

[0.9130434782608695, 0.8478260869565217, 0.8913043478260869]


In [31]:
print(KN)

[0.8913043478260869, 0.8478260869565217, 0.8586956521739131]


In [32]:
print(SVC_score)

[0.8695652173913043, 0.8586956521739131, 0.8586956521739131]


In [55]:
import joblib
joblib.dump(RF, "rf_model")

['rf_model']

In [56]:
X_test

array([[ 1, 55,  2, ...,  1,  1,  1],
       [ 1, 65,  2, ...,  1,  1,  1],
       [ 0, 67,  2, ...,  1,  1,  1],
       ...,
       [ 1, 55,  2, ...,  2,  1,  2],
       [ 1, 46,  1, ...,  1,  2,  2],
       [ 1, 60,  1, ...,  2,  2,  2]], dtype=int64)

In [57]:
mj = joblib.load('rf_model')

In [58]:
mj.predict([[1,55,2,1,1,1,1,2,1,1,1,1,1,1,1]])

array([0])

In [70]:
import pickle
pickle_out = open("pickle.pkl", "wb")
pickle.dump(RF,pickle_out)
pickle_out.close()